//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskScheduler.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentStatu
    {
        public string JobName { get; set; }
        public string CurrentStatus { get; set; }
        public System.DateTime LastRun { get; set; }
    }
}
