//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskScheduler.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTask
    {
        public string TaskId { get; set; }
        public string DestinationFolder { get; set; }
        public bool ToIncludeDate { get; set; }
        public string DateFormat { get; set; }
        public bool ToUnzip { get; set; }
        public bool ToDeleteOriginal { get; set; }
    }
}
