//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskScheduler.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderTrigger
    {
        public string TriggerID { get; set; }
        public string FolderToMonitor { get; set; }
        public string FileNameSubstring { get; set; }
        public Nullable<bool> FileNameIsExactMatch { get; set; }
        public string FileExtension { get; set; }
        public bool ToIncludeSubDirectories { get; set; }
    }
}
