//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskScheduler.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunTask
    {
        public string TaskId { get; set; }
        public string ProgramRunType { get; set; }
        public string ProgramLocation { get; set; }
        public string ProgramName { get; set; }
        public string ProgramCommaDelimParams { get; set; }
    }
}
