//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskScheduler.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskSchedulerEntities : DbContext
    {
        public TaskSchedulerEntities()
            : base("name=TaskSchedulerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmailTrigger> EmailTriggers { get; set; }
        public virtual DbSet<FileTask> FileTasks { get; set; }
        public virtual DbSet<FolderTrigger> FolderTriggers { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<RunTask> RunTasks { get; set; }
        public virtual DbSet<SharepointTrigger> SharepointTriggers { get; set; }
        public virtual DbSet<CurrentStatu> CurrentStatus { get; set; }
        public virtual DbSet<SQLTrigger> SQLTriggers { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TimeTrigger> TimeTriggers { get; set; }
    }
}
