//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskScheduler.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTrigger
    {
        public string TriggerID { get; set; }
        public System.DateTime FirstExecutionTime_EST_ { get; set; }
        public short ExecutionFrequency { get; set; }
        public string ExecutionFrequencyUnits { get; set; }
    }
}
